#!/bin/bash
# Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Test nvme-ep against an NVMe device (real or emulated).
# Writes sequential data via xio-tester, reads it back via
# nvme-cli, and verifies the data matches the expected LFSR
# pattern generated by xio-tester --dump-pattern.

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

NVME_DEVICE=""
LFSR_SEED="${LFSR_SEED:-0x1234}"
BASE_LBA="${BASE_LBA:-0}"
READ_IO="${READ_IO:-0}"
WRITE_IO="${WRITE_IO:-4}"
BLOCKS_PER_CMD="${BLOCKS_PER_CMD:-8}"
QUEUE_LENGTH="${QUEUE_LENGTH:-1024}"
DATA_BUFFER_SIZE="${DATA_BUFFER_SIZE:-1048576}"
MEMORY_MODE="${MEMORY_MODE:-0}"
USE_PCI_MMIO_BRIDGE="${USE_PCI_MMIO_BRIDGE:-1}"

XIO_TESTER="${XIO_TESTER:-./build/xio-tester}"
TEMP_DIR="${TEMP_DIR:-/tmp/nvme-ep-test}"
NVME_CMD="${NVME_CMD:-nvme}"

resolve_nvme_paths() {
    local device="$1"
    local real
    real="$(readlink -f "$device")" || return 1
    local node
    node="$(basename "$real")"

    if [[ "$node" =~ ^nvme[0-9]+n[0-9]+$ ]]; then
        local controller
        controller="$(basename "$(readlink -f \
            "/sys/class/block/$node/device")")" || return 1
        NVME_CONTROLLER="/dev/$controller"
        NVME_NAMESPACE="$device"
    else
        NVME_CONTROLLER="$real"
        NVME_NAMESPACE="${device}n1"
    fi
}

if [ $# -lt 1 ]; then
    echo "Usage: $0 <nvme-controller> [OPTIONS]"
    echo ""
    echo "Arguments:"
    echo "  <nvme-controller>   NVMe controller device"
    echo ""
    echo "Environment variables:"
    echo "  LFSR_SEED          LFSR seed (default: 0x1234)"
    echo "  BASE_LBA           Starting LBA (default: 0)"
    echo "  READ_IO            Read I/O count (default: 0)"
    echo "  WRITE_IO           Write I/O count (default: 4)"
    echo "  BLOCKS_PER_CMD     LBAs per command (default: 8)"
    echo "  MEMORY_MODE        0=host, 8=device (default: 0)"
    echo "  USE_PCI_MMIO_BRIDGE  0=no, 1=yes (default: 1)"
    exit 1
fi

NVME_DEVICE="$1"
shift

while [[ $# -gt 0 ]]; do
    case $1 in
        --seed|-s) LFSR_SEED="$2"; shift 2 ;;
        --base-lba|-b) BASE_LBA="$2"; shift 2 ;;
        --read-io|-r) READ_IO="$2"; shift 2 ;;
        --write-io|-w) WRITE_IO="$2"; shift 2 ;;
        --iterations|-i) WRITE_IO="$2"; shift 2 ;;
        --no-pci-mmio-bridge) USE_PCI_MMIO_BRIDGE="0"; shift ;;
        --help|-h)
            echo "Usage: $0 <nvme-controller> [OPTIONS]"
            echo "  --seed, -s <seed>       LFSR seed"
            echo "  --base-lba, -b <lba>    Starting LBA"
            echo "  --read-io, -r <num>     Read I/O count"
            echo "  --write-io, -w <num>    Write I/O count"
            echo "  --no-pci-mmio-bridge    Disable MMIO bridge"
            exit 0 ;;
        *)
            echo -e "${RED}Error: Unknown option $1${NC}"
            exit 1 ;;
    esac
done

mkdir -p "$TEMP_DIR"
TEST_LOG="$TEMP_DIR/test.log"

exec 3>&1 4>&2
exec 1>"$TEST_LOG" 2>&1

if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: requires root${NC}"
    exit 1
fi

if [ ! -e "$NVME_DEVICE" ]; then
    echo -e "${RED}Error: $NVME_DEVICE not found${NC}"
    exit 1
fi

if [ ! -f "$XIO_TESTER" ]; then
    echo -e "${RED}Error: xio-tester not found at $XIO_TESTER${NC}"
    exit 1
fi

if ! command -v "$NVME_CMD" &> /dev/null; then
    echo -e "${RED}Error: nvme-cli not found${NC}"
    exit 1
fi

get_lba_size() {
    local ns=$1

    local lbaf_line
    lbaf_line=$($NVME_CMD id-ns "$ns" 2>/dev/null \
        | grep "^lbaf" | grep "in use" | head -1)
    if [ -n "$lbaf_line" ]; then
        local lbads
        lbads=$(echo "$lbaf_line" | awk '{print $5}' \
            | cut -d: -f2)
        if [ -n "$lbads" ] && [ "$lbads" -ge 0 ] \
            2>/dev/null; then
            echo $((1 << lbads))
            return
        fi
    fi

    lbaf_line=$($NVME_CMD id-ns "$ns" 2>/dev/null \
        | grep "^lbaf" | head -1)
    if [ -n "$lbaf_line" ]; then
        local lbads
        lbads=$(echo "$lbaf_line" | awk '{print $5}' \
            | cut -d: -f2)
        if [ -n "$lbads" ] && [ "$lbads" -ge 0 ] \
            2>/dev/null; then
            echo $((1 << lbads))
            return
        fi
    fi

    echo 512
}

test_device() {
    local device=$1
    local NVME_CONTROLLER=""
    local NVME_NAMESPACE=""
    if ! resolve_nvme_paths "$device"; then
        echo "Error: failed to resolve NVMe paths for $device"
        return 1
    fi
    local ns="$NVME_NAMESPACE"
    local controller="$NVME_CONTROLLER"
    local device_name
    device_name=$(basename "$device")

    echo "========================================"
    echo "Testing NVMe: $device"
    echo "Controller: $controller"
    echo "Namespace: $ns"
    echo "========================================"

    local lba_size
    lba_size=$(get_lba_size "$ns")
    echo "LBA size: $lba_size bytes"

    local total_blocks=$((WRITE_IO * BLOCKS_PER_CMD))
    local total_bytes=$((total_blocks * lba_size))
    echo "Total data: $total_blocks blocks" \
        "($total_bytes bytes)"

    echo ""
    echo "Step 1: Writing data with nvme-ep..."

    local write_cmd="$XIO_TESTER nvme-ep -v"
    if [ "$READ_IO" -gt 0 ]; then
        write_cmd="$write_cmd --read-io $READ_IO"
    fi
    if [ "$WRITE_IO" -gt 0 ]; then
        write_cmd="$write_cmd --write-io $WRITE_IO"
    fi
    write_cmd="$write_cmd --controller $controller"
    if [ "$USE_PCI_MMIO_BRIDGE" = "1" ]; then
        write_cmd="$write_cmd --pci-mmio-bridge"
    fi
    write_cmd="$write_cmd --queue-length $QUEUE_LENGTH"
    write_cmd="$write_cmd --lfsr-seed $LFSR_SEED"
    write_cmd="$write_cmd --base-lba $BASE_LBA"
    write_cmd="$write_cmd --lbas-per-io $BLOCKS_PER_CMD"
    write_cmd="$write_cmd --access-pattern sequential"
    write_cmd="$write_cmd --batch-size 0"
    write_cmd="$write_cmd -m $MEMORY_MODE"
    if [ -n "${ROCXIO_NVME_QUEUE_ID:-}" ]; then
        write_cmd="$write_cmd --queue-id $ROCXIO_NVME_QUEUE_ID"
    fi

    echo "Command: $write_cmd"

    # shellcheck disable=SC2024
    if ! sudo $write_cmd \
        > "$TEMP_DIR/${device_name}_write.log" 2>&1; then
        echo "✗ Write failed"
        return 1
    fi

    local detected_lba_size
    detected_lba_size=$(grep -i "Selected LBA size" \
        "$TEMP_DIR/${device_name}_write.log" \
        | grep -oE "[0-9]+" | head -1)
    if [ -n "$detected_lba_size" ] \
        && [ "$detected_lba_size" != "$lba_size" ]; then
        echo "Warning: using detected LBA size:" \
            "$detected_lba_size bytes"
        lba_size=$detected_lba_size
        total_bytes=$((total_blocks * lba_size))
    fi

    echo "✓ Write completed"

    echo ""
    echo "Step 2: Reading data back..."

    local read_file="$TEMP_DIR/${device_name}_read.bin"
    local expected_file="$TEMP_DIR/${device_name}_expected.bin"
    local nvme_read_log="$TEMP_DIR/${device_name}_nvme_read.log"

    set +e
    $NVME_CMD read "$ns" \
        --start-block=$BASE_LBA \
        --block-count=$total_blocks \
        --data-size=$total_bytes \
        --data="$read_file" >"$nvme_read_log" 2>&1
    local nvme_read_rc=$?
    set -e
    if [ "$nvme_read_rc" -ne 0 ]; then
        echo "✗ Read failed (nvme exit $nvme_read_rc)"
        echo "  Command: $NVME_CMD read $ns" \
            "--start-block=$BASE_LBA" \
            "--block-count=$total_blocks" \
            "--data-size=$total_bytes" \
            "--data=$read_file"
        echo "  nvme-cli output ($nvme_read_log):"
        sed 's/^/    /' "$nvme_read_log" || true
        return 1
    fi

    echo "✓ Read completed"

    echo ""
    echo "Step 3: Generating expected pattern..."

    $XIO_TESTER --dump-pattern "$expected_file" \
        --dump-pattern-seed "$LFSR_SEED" \
        --dump-pattern-size "$total_bytes" \
        --dump-pattern-block-size "$lba_size" \
        --dump-pattern-offset 0 2>/dev/null

    echo "Step 4: Verifying data pattern..."

    local offset=0
    local all_match=true

    for ((i=0; i<WRITE_IO; i++)); do
        local lba=$((BASE_LBA + i * BLOCKS_PER_CMD))
        local block_size=$((BLOCKS_PER_CMD * lba_size))

        local expected_block
        expected_block="$TEMP_DIR/${device_name}_exp_${i}.bin"
        local read_block
        read_block="$TEMP_DIR/${device_name}_got_${i}.bin"

        dd if="$expected_file" of="$expected_block" \
            bs=1 skip=$offset count=$block_size \
            2>/dev/null
        dd if="$read_file" of="$read_block" \
            bs=1 skip=$offset count=$block_size \
            2>/dev/null

        if ! cmp -s "$read_block" "$expected_block"; then
            echo "✗ Iteration $i" \
                "(LBA $lba-$((lba + BLOCKS_PER_CMD - 1)))" \
                "mismatch"
            cmp -l "$read_block" "$expected_block" \
                2>/dev/null | head -10 \
                >> "$TEMP_DIR/${device_name}_mismatches.log" \
                || true
            all_match=false
        fi

        offset=$((offset + block_size))
    done

    if [ "$all_match" = true ]; then
        echo "✓ All data verified successfully!"
        return 0
    else
        echo "✗ Data verification failed"
        return 1
    fi
}

test_result=0
test_device "$NVME_DEVICE" || test_result=$?

exec 1>&3 2>&4
exec 3>&- 4>&-

pci_mmio_status=$([ "$USE_PCI_MMIO_BRIDGE" = "1" ] \
    && echo "pci-mmio" || echo "direct")
mem_mode_status=$([ "$MEMORY_MODE" = "8" ] \
    && echo "device-mem" || echo "host-mem")
test_params="seed=$LFSR_SEED base_lba=$BASE_LBA"
test_params="$test_params read=$READ_IO"
test_params="$test_params write=$WRITE_IO"
test_params="$test_params blocks=$BLOCKS_PER_CMD"
test_params="$test_params $pci_mmio_status $mem_mode_status"

if [ $test_result -eq 0 ]; then
    echo -e "${GREEN}PASS${NC}: $test_params" >&2
    exit 0
else
    echo -e "${RED}FAIL${NC}: $test_params" >&2
    exit 1
fi
