name: test-emulate

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'feat/**'
    paths:
      - '**.hip'
      - '**.cpp'
      - '**.c'
      - '**.h'
      - '**.hpp'
      - '**.cc'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'scripts/**'
      - 'Makefile'

jobs:
  test-emulate:
    name: test-emulate for rocm-xio
    runs-on: ubuntu-latest
    container:
      image: rocm/dev-ubuntu-24.04:7.2
      options: --user root
    env:
      LD_LIBRARY_PATH: /opt/rocm/lib:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
    steps:
    - name: Check out code.
      uses: actions/checkout@v5.0.0
    - name: Install additional dependencies
      run: |
        apt-get update
        apt-get install -y \
          cmake \
          curl \
          libcli11-dev \
          libdrm-dev
    - name: Build (with ROCm for compilation, but will run in emulate mode)
      run: |
        mkdir -p build && cd build
        cmake -DOFFLOAD_ARCH=gfx942:xnack+ \
          -DROCM_PATH=/opt/rocm \
          -DBUILD_TESTING=ON ..
        cmake --build . --target all
    - name: Run unit tests (CPU-only).
      run: |
        ctest --test-dir build -V -L "unit" \
          --parallel --output-on-failure
    - name: Run system-level CTests for test-ep emulate mode
      run: |
        ctest --test-dir build -V -L "system" -L "test-ep" \
          --output-on-failure
