# Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
#
# SPDX-License-Identifier: MIT

name: workflow-check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'feat/**'
    paths:
      - '.github/actions/**'
      - '.github/dependabot.yml'
      - '.github/workflows/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code.
      uses: actions/checkout@v5.0.0
    - name: Run actionlint
      uses: rhysd/actionlint@v1
